=== JoaoGome/PRI2020/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PR (header,workteam,abstract,derivables) >

<!ELEMENT header (titulo,subtitulo?,beginning_date, end_date, supervisor) >
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT beginning_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor
    link CDATA #IMPLIED>

<!ELEMENT workteam (elemento)+ >
<!ELEMENT elemento (nome, numero, mail) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT mail (#PCDATA) >
<!ATTLIST mail
    link CDATA #REQUIRED>

<!ELEMENT abstract (paragrafo)+ >
<!ELEMENT paragrafo (conteudo | link_interno | link_externo)+ >
<!ELEMENT conteudo (#PCDATA)>
<!ATTLIST conteudo 
    tipo (negrito|italico|sublinhado|normal) "normal" >
<!ELEMENT link_interno (#PCDATA) >
<!ATTLIST link_interno
    link IDREF #REQUIRED>
<!ELEMENT link_externo (#PCDATA) >
<!ATTLIST link_externo
    link CDATA #REQUIRED>
    
<!ELEMENT derivables (item)+ >
<!ELEMENT item (#PCDATA) >
<!ATTLIST item 
    link CDATA #REQUIRED>

=== JoaoGome/PRI2020/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "PR.dtd">
<PR>
    <header>
        <titulo>Relatório do TP2</titulo>
        <beginning_date>19/10/2020</beginning_date>
        <end_date>25/10/2020</end_date>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">José Ramalho</supervisor>
    </header>
    <workteam>
        <elemento>
            <nome>João Pedro Rodrigues Gomes</nome>
            <numero>A82238</numero>
            <mail link="My Email">a82238@alunos.uminho.pt</mail>
        </elemento>
    </workteam>
    <abstract>
        <paragrafo>
            <conteudo tipo="normal">Para este TPC, tivemos de escrever um DTD que modulasse Public Records. </conteudo>
        </paragrafo>
    </abstract>
    <derivables>
        <item link="./PR.dtd">DTD correspondente</item>
    </derivables>
</PR>
